export default {

    // TabNavigator
    HomeTabScreen: 'HomeTabScreen',
    PostNewItemScreen: "PostNewItemScreen",
    MyResponsesScreen: "MyResponsesScreen",
    ProfileScreen: "ProfileScreen",

    // AppNavigator
    HomeScreen: "HomeScreen",
    AboutScreen: "AboutScreen",
    BuySellEditScreen: "BuySellEditScreen",
    BuySellFeedScreen: "BuySellFeedScreen",
    BuySellProductDetailsScreen: "BuySellProductDetailsScreen",
    ChatsScreen: "ChatsScreen",
    ChatRoomScreen: "ChatRoomScreen",
    ChangePasswordScreen: "ChangePasswordScreen",
    ChangeThemeScreen: "ChangeThemeScreen",
    EditLostFoundItemScreen: "EditLostFoundItemScreen",
    EditProfileScreen: "EditProfileScreen",
    EditRequirementsScreen: "EditRequirementsScreen",
    EmailSignUpScreen: "EmailSignUpScreen",
    EmailOTPScreen: "EmailOTPScreen",
    LostFoundFeedScreen: "LostFoundFeedScreen",
    LostFoundProductDetailsScreen: "LostFoundProductDetailsScreen",
    MyBuySellItemsScreen: "MyBuySellItemsScreen",
    MyLostFoundItemsScreen: "MyLostFoundItemsScreen",
    MyRequirementsScreen: "MyRequirementsScreen",
    NotificationsPreferenceScreen: "NotificationsPreferenceScreen",
    RequirementsFeedScreen: "RequirementsFeedScreen",
    IntroductionScreen: "IntroductionScreen",
    LoginScreen: "LoginScreen",
    SignUpScreen: "SignUpScreen",
    SettingsScreen: "SettingsScreen",
    PostNewBuyItemScreen: "PostNewBuyItemScreen",
    PostNewLostItemScreen: "PostNewLostItemScreen",
    PostNewRequirementScreen: "PostNewRequirementScreen",
    RaiseHandOnItemScreen: "RaiseHandOnItemScreen",
    ResetPasswordScreen: "ResetPasswordScreen",
}