// Auth Action Types
export const UPDATE_COUNT = "UPDATE_COUNT";
export const UPDATE_RAISED_HANDS_COUNT = "UPDATE_RAISED_HANDS_COUNT";
export const UPDATE_UNREAD_MESSAGES_COUNT = "UPDATE_UNREAD_MESSAGES_COUNT";
export const RESET = "RESET";